### ISSUE TITLE
How to change tha number of channel vocoder

### ISSUE THREAD

**Issue by epriwahyu** [Mary-prh/CIS-Strategy-for-Cochlear-Implant-code-in-Matlab#1]
Is it correct that if I want to change the number of channel (example: 8 channel vocoder", we only need to change the number in "Channels"?

`Channels = 8;
ChBand = 500;
OutputSig = 0;`

Thanks

**Comment by Mary-prh** [comment]
Yes, But beforehand, you may want to save the last two functions separately in the same directory and run the rest of the code.

**Comment by epriwahyu** [comment]
thanks!
